[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
base85 = "2.0.0"
hex = "0.4.3"
regex = "1.10.4"
serde_json = "1.0.117"
sha2 = "0.10.8"
walkdir = "2.5.0"

[[bin]]
name = "image_to"
path = "src/image_to_base85_hash.rs"
